// ** Mock
import mock from 'src/@fake-db/mock'

// ** Types
import { UsersType } from 'src/types/manage/userTypes'

const data: { users: UsersType[] } = {
  users: [
    {
      id: 1,
      client_cod: '',
      fullName: 'ADMINISTRADOR XPROP',
      username: 'admin',
      password: '',
      email: 'admin@xprop.com.br',
      telephone: '',
      cellphone: '',
      taxid: '17245830493',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'admin',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/1.png',
      currentPlan: 'team'
    },
    {
      id: 2,
      client_cod: '',
      fullName: 'SCRIPT NIC',
      username: 'script',
      password: '',
      email: 'script@xprop.com.br',
      telephone: '',
      cellphone: '',
      taxid: '45801797020',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'realAccountAdmin',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/2.png',
      currentPlan: 'team'
    },
    {
      id: 3,
      client_cod: '',
      fullName: 'SAYMON GOVEA',
      username: 'saymon',
      password: '',
      email: 'saymon@xprop.com.br',
      telephone: '',
      cellphone: '',
      taxid: '40133904194',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'testAccountAdmin',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/3.png',
      currentPlan: 'team'
    },
    {
      id: 4,
      client_cod: '',
      fullName: 'NICOLAU CASTRO',
      username: 'nicolau',
      password: '',
      email: 'nicolau@xprop.com.br',
      telephone: '',
      cellphone: '',
      taxid: '32330174041',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'financial',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/4.png',
      currentPlan: 'team'
    },
    {
      id: 5,
      client_cod: '',
      fullName: 'FELIPE BRANDAO',
      username: 'felipe',
      password: '',
      email: 'felipe@xprop.com.br',
      telephone: '',
      cellphone: '',
      taxid: '23747013410',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'support',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/5.png',
      currentPlan: 'team'
    },
    {
      id: 6,
      client_cod: '',
      fullName: 'USUÁRIO RESTRITO',
      username: 'restrito',
      password: '',
      email: 'restrito@xprop.com.br',
      telephone: '',
      cellphone: '',
      taxid: '54170429201',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'restricted',
      status: 'inactive',
      lgpd_check: '',
      avatar: '/images/avatars/6.png',
      currentPlan: 'team'
    },
    {
      id: 7,
      client_cod: '',
      fullName: 'JEFFERSON ALVES DE SOUZA',
      username: 'jeffalves',
      password: '',
      email: 'sza.jeff@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '75147390147',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/7.png',
      currentPlan: 'team'
    },
    {
      id: 8,
      client_cod: '',
      fullName: 'MARIA ADRIANE SANTOS DIAS',
      username: 'mariadias',
      password: '',
      email: 'adrianetrader7@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '25904712947',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'pending',
      lgpd_check: '',
      avatar: '/images/avatars/8.png',
      currentPlan: 'team'
    },
    {
      id: 9,
      client_cod: '',
      fullName: 'LUCAS RICARDO DE CASTRO SILVA',
      username: 'lucastro',
      password: '',
      email: 'lucasricardo@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '03404719281',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/9.png',
      currentPlan: 'team'
    },
    {
      id: 10,
      client_cod: '',
      fullName: 'JOAO PAULO DA COSTA ALMEIDA',
      username: 'jpcosta',
      password: '',
      email: 'joao.pauloq28@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '01347954135',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'inactive',
      lgpd_check: '',
      avatar: '/images/avatars/10.png',
      currentPlan: 'team'
    },
    {
      id: 11,
      client_cod: '',
      fullName: 'RENATO CORREA LEITE GUIMARAES',
      username: 'renatoclg',
      password: '',
      email: 'renatocorrealeiteguimaraes@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '94194364134',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/11.png',
      currentPlan: 'team'
    },
    {
      id: 12,
      client_cod: '',
      fullName: 'ANA PAULA CARDOSO DE MORAES',
      username: 'anapaula_c',
      password: '',
      email: 'anacardoso5@hotmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '91634163394',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/12.png',
      currentPlan: 'team'
    },
    {
      id: 13,
      client_cod: '',
      fullName: 'MATEUS VINICIUS BATISTA DE AZEVEDO',
      username: 'batista123',
      password: '',
      email: 'mateusvinicius0001@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '15919635395',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/13.png',
      currentPlan: 'team'
    },
    {
      id: 14,
      client_cod: '',
      fullName: 'BRUNO LEONARDO SOUZA PAZ',
      username: 'bruno_leo',
      password: '',
      email: 'bruno_leonardo_paz@outlook.zky',
      telephone: '',
      cellphone: '',
      taxid: '43649356342',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'pending',
      lgpd_check: '',
      avatar: '/images/avatars/14.png',
      currentPlan: 'team'
    },
    {
      id: 15,
      client_cod: '',
      fullName: 'MARCELO MARCOLINO GALVAO SANTOS',
      username: 'marcelosantos',
      password: '',
      email: 'marcelo.marcolino.123@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '34962565625',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/15.png',
      currentPlan: 'team'
    },
    {
      id: 16,
      client_cod: '',
      fullName: 'WESLEY DIEGO GONCALVES DE OLIVEIRA',
      username: 'wdgoliveira',
      password: '',
      email: 'wesleydgdo97@yahoo.zky.br',
      telephone: '',
      cellphone: '',
      taxid: '04174157417',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/16.png',
      currentPlan: 'team'
    },
    {
      id: 17,
      client_cod: '',
      fullName: 'PEDRO HENRIQUE MOREIRA SODRE EGIDIO',
      username: 'pedroegidio',
      password: '',
      email: 'phsodre@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '55604172504',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/17.png',
      currentPlan: 'team'
    },
    {
      id: 18,
      client_cod: '',
      fullName: 'DANILO NIIUCHI SILVA',
      username: 'niiuchi',
      password: '',
      email: 'danvi.niiuchi@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '17285401728',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'inactive',
      lgpd_check: '',
      avatar: '/images/avatars/18.png',
      currentPlan: 'team'
    },
    {
      id: 19,
      client_cod: '',
      fullName: 'FELIPE RICARDO PRADO DE OLIVEIRA',
      username: 'feliprado',
      password: '',
      email: 'fe.hardy02@hotmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '54012850412',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/19.png',
      currentPlan: 'team'
    },
    {
      id: 20,
      client_cod: '',
      fullName: 'DANIEL DE OLIVEIRA GALLI',
      username: 'galli',
      password: '',
      email: 'danielgalli@yahoo.zky.br',
      telephone: '',
      cellphone: '',
      taxid: '85741359457',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/20.png',
      currentPlan: 'team'
    },
    {
      id: 21,
      client_cod: '',
      fullName: 'ARIEL HORACIO ACUNA',
      username: 'ariel_ha',
      password: '',
      email: 'ariel@tds-consulting.zky',
      telephone: '',
      cellphone: '',
      taxid: '45830417293',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/21.png',
      currentPlan: 'team'
    },
    {
      id: 22,
      client_cod: '',
      fullName: 'FLAVIA APARECIDA DE OLIVEIRA',
      username: 'oliveira_flavia',
      password: '',
      email: 'oliveiraflavia2627@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '01797045820',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/22.png',
      currentPlan: 'team'
    },
    {
      id: 23,
      client_cod: '',
      fullName: 'ERICO PEREIRA DE SOUSA',
      username: 'ericopereira',
      password: '',
      email: 'ericopbs@hotmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '39041401394',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'inactive',
      lgpd_check: '',
      avatar: '/images/avatars/23.png',
      currentPlan: 'team'
    },
    {
      id: 24,
      client_cod: '',
      fullName: 'JULIA BOSCO MAFRA',
      username: 'juliabmafra',
      password: '',
      email: '07juliabosco@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '30174323041',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/24.png',
      currentPlan: 'team'
    },
    {
      id: 25,
      client_cod: '',
      fullName: 'GABRIEL LUZ COSTA',
      username: 'gabriel_costa',
      password: '',
      email: 'gabrielluzc@outlook.zky.br',
      telephone: '',
      cellphone: '',
      taxid: '74701323410',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'pending',
      lgpd_check: '',
      avatar: '/images/avatars/25.png',
      currentPlan: 'team'
    },
    {
      id: 26,
      client_cod: '',
      fullName: 'LETICIA CAROLINE DOS SANTOS',
      username: 'letisantos',
      password: '',
      email: 'leeticiacs03@gmail.zky',
      telephone: '',
      cellphone: '',
      taxid: '17042925401',
      birthdate: '',
      address_street: '',
      address_number: '',
      complement: '',
      zip: '',
      district: '',
      city: '',
      state: '',
      country: '',
      role: 'client',
      status: 'active',
      lgpd_check: '',
      avatar: '/images/avatars/26.png',
      currentPlan: 'team'
    }
  ]
}

// POST: Add new user
mock.onPost('/manage/users/add-user').reply(config => {
  // Get event from post data
  const user = JSON.parse(config.data).data

  const { length } = data.users
  let lastIndex = 0
  if (length) {
    lastIndex = data.users[length - 1].id
  }
  user.id = lastIndex + 1

  data.users.unshift({ ...user, avatar: '', avatarColor: 'primary', status: 'active' })

  return [201, { user }]
})

// GET: Updated DATA
mock.onGet('/manage/users/list').reply(config => {
  const { q = '', role = null, status = null, currentPlan = null } = config.params ?? ''

  const queryLowered = q.toLowerCase()

  const filteredData = data.users.filter(
    user =>
      (user.username.toLowerCase().includes(queryLowered) ||
        user.fullName.toLowerCase().includes(queryLowered) ||
        user.role.toLowerCase().includes(queryLowered) ||
        (user.email.toLowerCase().includes(queryLowered) &&
          user.currentPlan.toLowerCase().includes(queryLowered) &&
          user.status.toLowerCase().includes(queryLowered))) &&
      user.role === (role || user.role) &&
      user.currentPlan === (currentPlan || user.currentPlan) &&
      user.status === (status || user.status)
  )

  return [
    200,
    {
      allData: data.users,
      users: filteredData,
      params: config.params,
      total: filteredData.length
    }
  ]
})

// GET: particular user data
mock.onGet('/manage/user').reply(config => {
  const { id } = config.params

  const userData = data.users.filter(user => user.id === parseInt(id, 10))

  if (userData.length) {
    return [200, userData[0]]
  } else {
    return [404, { message: 'Unable to find the requested user!' }]
  }
})

// DELETE: Deletes User
mock.onDelete('/manage/users/delete').reply(config => {
  // Get user id from URL
  const userId = config.data

  const userIndex = data.users.findIndex(t => t.id === userId)
  data.users.splice(userIndex, 1)

  return [200]
})
